# my_set = set()
# my_set.add(1)
# my_set.add(2)
# my_set.add(3)
# my_set.add(4)
# my_set.add(4)
# set2 = set(['one','two','three'])
# print(my_set)
# print(type(my_set))
# print(len(my_set))
# set3 = set2.update(my_set)
# print(set3)
# set1= set('aaabc')
# print(set1)
# print(type(set1))

#myset = set([1, 2, 3,'a','b'])
# myset.update('abc')
# print(myset)
# #myset.remove('d')
# myset.discard('d')
# print(myset)
# myset.clear()
# print(myset)
# for val in myset:
#     print(val)
# if 'd' in myset:
#     print('d is not present')
set1 = set([1,2,3,4,5,6])
set2 = set([5,6,7,8,9,10])
#print(set1.union(set2))
#print(set1 | set2)
#print(set1.intersection(set2))
#print(set1 & set2)
#print(set1.difference(set2))
#print(set1 - set2)
#print(set1.symmetric_difference(set2))
#print(set1 ^ set2)
set1 = set([1,2,3,4,5,6])
set2 = set([5,6])
# print(set2.issubset(set1))
#print(set2 <= set1)
print(set1 >= set2)